# Google Cloud Configuration for Streamlit Cloud
[gcp_service_account]
type = "service_account"
project_id = "kalaconnect-hackathon"
private_key_id = "c3df2c3d223f8417b7ca34b02259cc16fb1d94a8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCywt1UMcyZMrOP
XJRM5gTc5IUwz3NgZEbYeOPuwpSd35Eg+8t9PY7Jbythzc9028Hf5eONHwcNcpxV
/zrcb6stmHEqFN1kGrjIhaOpY57NWxDd2CI5+9uaSLbkeqCgIlkKP9XwnAJu7nEU
Fn6DECmZ93EQyg45nnPYleX7BbY57gE1YttdSDdOODlnf5HsAZR8f+Y949r71c/j
d6CggZzDz+QxZYvlXKE/ROtLekeh5hMiuvLXOD5lxysHAsB2X3lkOD/MsW/OruCJ
8DbME8VosmNY2tKN40CztMUhzvuakoT3q3y3vex5rBdqP+wLR+nN2ZI3LlLFYzHL
LC3BGYwXAgMBAAECggEADRJ77fLAU/mlsNejzqXJeD/Lz6Bz/voGRkE85dJb3Nmi
+sb+//cW8HsNMJdE0vZZDJ76j3DT6rNVZGKIMuOFoI1zxRCGihH8Lkm7iKEM1VaR
+q8Z/aSB0Bv+J+IhyeQJH9tAMVqvQN517XKhqMLvT9+M6J3mAWepcA6yJTOrOjwi
iJW6cOYWleml3e7jukADJajQyeo8oksAwcAM+x+/6tW2Ih13DKrF4xS6tA/zsq7q
NERRy/k4aRRQvj5eIAbShdAZWYKxnI7CwoMwcnmYzTgJjXzlsByP9je7+Hg050ph
yC4uPsw1EMImNdCwKL/liNbZi3YCkxpNw9Hi/ulCOQKBgQDjlHBQL84161k0AL86
D1yGsOM4OOqSQtxBmmJo2hAVFPo+vuRkSbTJxcf4m9Hs0o4VQmlT+jD9bj3PVGgB
cguB7mXR/XLh3ESuUeuEPtmz4jiFD7lrrAEMZmiq7T2Ux5OhHfb7ecaVyrVXU4CU
y6VciR+TFUo09ozOb2lBAIIlyQKBgQDJFbqx7LvegUeRzZd4hNCRPrNUzRJcUy6K
6B1uhJ8lT7gU7/muUXFGB0bZKgAhnrp4uaTQVqF5aZiXahyprrr6ccF8tPzYZYIV
TkToF94ma82O06tr5y9qE+P0zX2k699ln4lElqP9L3kkdf64oXcAgKqXkTxHaeLe
NeF9M76S3wKBgEkvC+sNZH+8XiQ19UijdfquWXNUAkLkk1XZYrobHb7ZzxtsYZ/K
gAO+wW62FQzWLPCzOZHSy/xDfkb0+rk0RnUTB9U+bropDkEMgPM3DuUk404O3267
kl69c/07a2kzwMq4CxuVboHu/N/HL3sp/dRDGE9BMmrTujYMZ8mKc0/ZAoGBAJpa
7rPTmCblsA2Q9pvRv9QugDQxMs3iIFEKekUy0oMunYyc5VlVNRFfVpgusGkeUd+I
CabPSSZM05AvKQ9rjCXhGnhi6dAmo2M9cJGEeMefauwfOXAbx36zBAIPl0n4scRt
YU5gIEOipGhDlyMc9p9RJSIxn0bmVfri+1NDXB+bAoGBAOGqDCJzLGcuKZ36ScH+
htU1gbPsm9InQcvUwYjG2SE8nCDFLKr2XhBZnH/uQUykKJD7FNTLfnPvI3NIPfIb
ewk4aKjhabQjHPB5PhwH+49zisVtqjYa56IObOj8URr1rJJMTF4fptZ1EVvZrIzf
g9f1aOuket1b7sl568ajOB9t
-----END PRIVATE KEY-----"""
client_email = "kalaconnect-app@kalaconnect-hackathon.iam.gserviceaccount.com"
client_id = "113975566461985039817"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
universe_domain = "googleapis.com"

# Additional configuration
GOOGLE_API_KEY = "AIzaSyCNhzjwTJEJoDytubfmXIpozWJ3qFz7U2w"
GOOGLE_CLOUD_PROJECT = "kalaconnect-hackathon"