# Google Cloud Configuration
GOOGLE_API_KEY = "AIzaSyCNhzjwTJEJoDytubfmXIpozWJ3qFz7U2w"
GOOGLE_APPLICATION_CREDENTIALS = "E:\\KalaConnect\\kalaconnect-app-key.json"

# You can also add your project ID here for clarity
GOOGLE_CLOUD_PROJECT = "kalaconnect-hackathon"